version: '3.8'
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latest
    container_name: mariadb_c
    volumes:
      - mariadb_db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:latest
    container_name: wordpress_c
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
      - redis
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_ROOT_PASSWORD=${WORDPRESS_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      # Wordpress website configuration
      - WORDPRESS_SITE_TITLE=${WORDPRESS_SITE_TITLE}
      #   ADMIN user
      - WORDPRESS_SITE_ADMIN_USER=${WORDPRESS_SITE_ADMIN_USER}
      - WORDPRESS_SITE_ADMIN_PASSWORD=${WORDPRESS_SITE_ADMIN_PASSWORD}
      - WORDPRESS_SITE_ADMIN_EMAIL=${WORDPRESS_SITE_ADMIN_EMAIL}
      #   REGULAR user
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WORDPRESS_SITE_USER=${WORDPRESS_SITE_USER}
      - WORDPRESS_SITE_USER_PASSWORD=${WORDPRESS_SITE_USER_PASSWORD}
      - WORDPRESS_SITE_USER_EMAIL=${WORDPRESS_SITE_USER_EMAIL}
    networks:
      - inception_net
    restart: always
  
  nginx:
    build: ./requirements/nginx
    image: nginx:latest
    container_name: nginx_c
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_net
# ============================= Bonus part ===============================
  redis:
    build: ./requirements/bonus/redis
    image: redis:latest
    container_name: redis_c
    restart: always
    networks:
      - inception_net

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:latest
    container_name: ftp_c
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/home/${FTP_USER}/ftp/files
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    restart: always
    networks:
      - inception_net

  static:
    build: ./requirements/bonus/static
    image: static:latest
    container_name: static_c
    ports:
      - "88:88"
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:latest
    container_name: adminer_c
    depends_on:
      - mariadb
    ports:
      - "81:81"
    restart: always
    networks:
      - inception_net
  
  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor:latest
    container_name: cadvisor_c
    ports:
      - "8888:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/dev/kmsg:/dev/kmsg"
    privileged: true
    restart: always

# ============================= Volumes and stuff ==========================
volumes:
    mariadb_db:
      driver_opts:
        type: none
        o: bind
        device: /home/haitkadi/data/db     
    wordpress_vol:
      driver_opts:
        type: none
        o: bind
        device: /home/haitkadi/data/site-files
networks:
      inception_net:
        driver: bridge
 
 
