version: '3.8'
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latest
    container_name: mariadb_c
    volumes:
      - mariadb_db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - np
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:latest
    container_name: wordpress_c
    volumes:
      - wordpress_db:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - ./.env
    networks:
      - np
    restart: always
  
  nginx:
    build: ./requirements/nginx
    image: nginx:latest
    container_name: nginx_c
    depends_on:
      - wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress_db:/var/www/html
    ports:
      - "443:443"
      - "88:80"
    restart: always
    networks:
      - np

volumes:
    mariadb_db:
      driver_opts:
        type: none
        o: bind
        device: /home/ubuntu/data/db     
    wordpress_db:
      driver_opts:
        type: none
        o: bind
        device: /home/ubuntu/data/site-files
networks:
      np:
        driver: bridge
 
 
