version: '3.8'
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latest
    container_name: mariadb_c
    volumes:
      - mariadb_db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - np
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:latest
    container_name: wordpress_c
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - ./.env
    networks:
      - np
    restart: always
  
  nginx:
    build: ./requirements/nginx
    image: nginx:latest
    container_name: nginx_c
    depends_on:
      - wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    restart: always
    networks:
      - np
# ============================= Bonus part ===============================
  redis:
    build: ./requirements/bonus/redis
    image: redis:latest
    container_name: redis_c
    restart: always
    networks:
      - np

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:latest
    container_name: ftp_c
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/home/${FTP_USER}/ftp/files
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    restart: always
    networks:
      - np

  static:
    build: ./requirements/bonus/static
    image: static:latest
    container_name: static_c
    ports:
      - "88:88"
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:latest
    container_name: adminer_c
    depends_on:
      - mariadb
    ports:
      - "81:81"
    restart: always
    networks:
      - np
# ============================= Volumes and stuff ==========================
volumes:
    mariadb_db:
      driver_opts:
        type: none
        o: bind
        device: /home/haitkadi/data/db     
    wordpress_vol:
      driver_opts:
        type: none
        o: bind
        device: /home/haitkadi/data/site-files
networks:
      np:
        driver: bridge
 
 
